### ISSUE TITLE
Custom surround doesn't seem to work

### ISSUE THREAD

**Issue by tng2903** [yatki/vscode-surround#3]
Hello, I'm trying to add a new custom surround snippet as below

    "surround.custom": {
        "yourCommandName": {
            // label must be unique
            "label": "Your Snippet Label",
            "disabled": false,
            "description": "Your Snippet Description",
            "snippet": "burrito { $TM_SELECTED_TEXT }$0" // <-- snippet goes here.
          },
    },

Yes, it's actually the demo from your readme, but it doesn't get generated or seem to run. Did I do anything wrong?

**Comment by yatki** [comment]
@tng2903 Thank you very much for reporting the issue. 

You were doing nothing wrong. There was a weird bug but it should be fixed with v1.0.2.

Please update the extension and let me know if you are experiencing the same issue :) 

Have a great week.

**Comment by sepehrooo** [comment]
Hi there,
I'm on V1.0.2 and the demo from your readme is still not working for me. Here's what I put in settings.json:

```
        "surround.custom": {
		// command name must be unique
		"yourCommandName": {
			// label must be unique
			"label": "Your Snippet Label",
			"description": "Your Snippet Description",
			"snippet": "burrito { $TM_SELECTED_TEXT }$0" // <-- snippet goes here.
		}
	}
```

**Comment by yatki** [comment]
@sepehrooo I just checked it and looks like it's working fine. Can you make sure there are no comma issues etc. as long as JSON format is correct the configuration you copied here should work fine.
